# -*- mode: ruby -*-
# vi: set ft=ruby :


MASTER_IP       = "192.168.50.4"
NODE_01_IP      = "192.168.50.5"
# NODE_02_IP      = "192.168.50.6"


Vagrant.configure("2") do |config|
  
  config.vm.box = "ubuntu/jammy64"
  boxes = [
    { :name => "master",  :ip => MASTER_IP,  :cpus => 2, :memory => 2048 },
    { :name => "node-01", :ip => NODE_01_IP, :cpus => 2, :memory => 2048 },
    # remove the comment below or add additional nodes as required 
    # { :name => "node-02", :ip => NODE_02_IP, :cpus => 1, :memory => 1024 },
  
  ]

  boxes.each do |opts|
    config.vm.define opts[:name] do |box|
      box.vm.hostname = opts[:name]
      box.vm.network :private_network, ip: opts[:ip]
 
      box.vm.provider "virtualbox" do |vb|
        vb.cpus = opts[:cpus]
        vb.memory = opts[:memory]
      end
      box.vm.provision "shell", path:"./kube-install.sh"
      if box.vm.hostname == "master" then 
        box.vm.provision "shell", path:"./master.sh"
        end
      if box.vm.hostname == "node-01" then
        box.vm.provision "shell", path:"./workers.sh"
      end
      # if box.vm.hostname == "node-02" then
      # box.vm.provision "shell", path:"./workers.sh"
      # end
    end
  end
end

 